apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - port: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-app-service
  labels:
    app: greeting
spec:
  selector:
    app: greeting
  ports:
    - port: 8086
