apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
   - name: my-nginx
     image: nginx:alpine
     readinessProbe:
       httpGet:
         path: /index.html
         port: 80
       initialDelaySeconds: 15
     ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
    - name: html-updater
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - while true; do date >> /usr/share/nginx/html/index.html;sleep 10;done
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
  labels:
    app: hostpath
spec:
  containers:
    - name: docker
      image: docker
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket

